password: testpassword123!@#
encrypt_type: aes
target_paths:
  - /workspace/single_test
obfuscate_suffix: .dat
obfuscate_name_length: 12
map_filename: .app_encrypt
lock_filename: .encrypt.lock
map_storage_path: /workspace/tmp
