Password: "testpassword123!@#"
EncryptType: "aes"
TargetPaths:
  - "/workspace/test_data"
ObfuscateSuffix: ".dat"
ObfuscateNameLength: 12
MapFilename: ".app_encrypt"
LockFilename: ".encrypt.lock"
MapStoragePath: "/workspace/tmp"
Salt: ""
